### ISSUE TITLE
livestreming from android isn't stoping even after calling stopVideoStreaming 

### ISSUE THREAD

**Issue by AnAnD4T1** [pinkfish/flutter_rtmppublisher#12]

**Comment by Nijinsha** [comment]
Same issue.

**Comment by pinkfish** [comment]
Just fixed this.  Update to the newest version.

**Comment by AnAnD4T1** [comment]
now when stream starting it shows failed to configure camera session

**Comment by AnAnD4T1** [comment]
V/Camera  (27988): createCaptureSession
W/CameraDevice-JV-0(27988): Stream configuration failed due to: endConfigure:503: Camera 0: Unsupported set of inputs/outputs provided
E/CameraCaptureSession(27988): Session 1: Failed to create capture session; configuration failed
I/flutter (27988): Event {errorDescription: Failed to configure camera session., eventType: error}

**Comment by pinkfish** [comment]
Latest version failed to upload apparently.  Uploaded now.

**Comment by AnAnD4T1** [comment]
i used latest from git

**Comment by Nijinsha** [comment]
Experiencing some issue with camera configuration

**Comment by pinkfish** [comment]
Which version of the android api are you running with?

**Comment by AnAnD4T1** [comment]
minSdkVersion 21
compileSdkVersion 28

**Comment by adminant** [comment]
Same issue after upgrading from 0.1.9 to 0.2.1 version of plugin.
Start video streaming leads to error:

E/CameraDevice-0-LE(29360): submitRequestList - cannot use a surface that wasn't configured
I/flutter (29360): Event {eventType: error, errorDescription: CAMERA_ERROR (3): submitRequestList - cannot use a surface that wasn't configured}

Nothing changed in app, only plugin version to 0.2.1.
build.gradle settings:
        minSdkVersion 21
        targetSdkVersion 28

**Comment by Nijinsha** [comment]
Any update on this?

**Comment by adminant** [comment]
Updated to 0.2.2, but still the same error(

**Comment by AnAnD4T1** [comment]
Any update

**Comment by adminant** [comment]
I managed to discover that Android virtual Pixel 2 API 28 device works nice on 0.2.2 (except that video is still rotated 90 degree).

**Comment by adminant** [comment]
Further experiments showed that "androidUseOpenGL" parameter helps to get rid of error. Use it like this in example's startVideoStreaming function:

await controller.startVideoStreaming(url, bitrate: 1200 * 1024, androidUseOpenGL: true);
instead of 
await controller.startVideoStreaming(url);
