### ISSUE TITLE
Do I have to change the link if I want to upload the recording into MediaLive of AWS?

### ISSUE THREAD

**Issue by wann2** [pinkfish/flutter_rtmppublisher#13]
Hi,
I am a novice in RTMP.
I'd like to upload the camera recording on the phone into the MediaLive of AWS.
I have found the below in your sample codes.

TextEditingController(text: "rtmp://34.70.40.166:1935/LiveApp/815794454132232781694481");

If I change the above rtmp url into the MediaLive of AWS, do it can upload the camera recording?

**Comment by adminant** [comment]
Yes, change this example address to your MediaLive RTMP server address, and start streaming.

**Comment by wann2** [comment]
Thanks for the answer.
When I set AWS MediaLive, it gives 2 rtmp endpoint urls. How can I set the 2 rtmp urls inside your sample codes?

**Comment by adminant** [comment]
As far as I know these two urls are for redundancy, so you can use first of them

**Comment by wann2** [comment]
Thanks for the guide.

I changed the rtmp url of your Flutter sample codes with my own MediaLive's rtmp url.

I started MediaLive channel.

When I click Icons.ondemand_video to execute onRecordingAndVideoStreamingButtonPressed and from the popup dialog I click OK,
then I got null error on snackbar.
and the below error displayed.

MethodChannel#plugins.flutter.io/camera_with_rtmp: Failed to handle method call
    kotlin.KotlinNullPointerException
        at com.whelksoft.camera_with_rtmp.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.kt:93)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)

I wonder if the above error is related to MediaLive setting.
or could I get any idea what is wrong?

**Comment by adminant** [comment]
I would suggest to try not startVideoRecordingAndStreaming, but startVideoStreaming method (on example page it's shown as a watch afaik). But in current version of plugin 0.2.2 it leads to error as discussed in thread ["livestreming from android isn't stoping even after calling stopVideoStreaming "](https://github.com/pinkfish/flutter_rtmppublisher/issues/12)

**Comment by wann2** [comment]
When I use 0.1.9, I get the below build error.

e: /Users/momoland/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/camera_with_rtmp-0.1.9/android/src/main/kotlin/com/whelksoft/camera_with_rtmp/Camera.kt: (33, 7): Redeclaration: Camera
e: /Users/momoland/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/camera_with_rtmp-0.1.9/android/src/main/kotlin/com/whelksoft/camera_with_rtmp/MethodCallHandlerImpl.kt: (14, 16): Redeclaration: MethodCallHandlerImpl
e: /Users/momoland/Downloads/flutter_rtmppublisher-master/android/src/main/kotlin/com/whelksoft/camera_with_rtmp/Camera.kt: (33, 7): Redeclaration: Camera
e: /Users/momoland/Downloads/flutter_rtmppublisher-master/android/src/main/kotlin/com/whelksoft/camera_with_rtmp/MethodCallHandlerImpl.kt: (14, 16): Redeclaration: MethodCallHandlerImpl
e: /Users/momoland/Downloads/flutter_rtmppublisher-master/android/src/main/kotlin/com/whelksoft/camera_with_rtmp/MethodCallHandlerImpl.kt: (79, 25): Type mismatch: inferred type is Boolean but MethodChannel.Result was expected
e: /Users/momoland/Downloads/flutter_rtmppublisher-master/android/src/main/kotlin/com/whelksoft/camera_with_rtmp/MethodCallHandlerImpl.kt: (80, 25): Too many arguments for public final fun startVideoStreaming(url: String?, bitrate: Int?, result: MethodChannel.Result): Unit defined in com.whelksoft.camera_with_rtmp.Camera
e: /Users/momoland/Downloads/flutter_rtmppublisher-master/android/src/main/kotlin/com/whelksoft/camera_with_rtmp/MethodCallHandlerImpl.kt: (96, 25): Type mismatch: inferred type is Boolean but MethodChannel.Result was expected
e: /Users/momoland/Downloads/flutter_rtmppublisher-master/android/src/main/kotlin/com/whelksoft/camera_with_rtmp/MethodCallHandlerImpl.kt: (97, 25): Too many arguments for public final fun startVideoRecordingAndStreaming(filePath: String, url: String?, bitrate: Int?, result: MethodChannel.Result): Unit defined in com.whelksoft.camera_with_rtmp.Camera

FAILURE: Build failed with an exception.


When I use 0.2.2, then the build is OK, 
but when I execute startVideoStreaming, 
"Camera error Failed to configure camera session" error happens.
I tested at Samsung Galaxy 6 and Samsung Note 5. Both of them got the error.

![KakaoTalk_Photo_2020-06-06-17-25-19](https://user-images.githubusercontent.com/8732515/83939808-bbb46800-a81a-11ea-81b0-2609c3a464cf.jpeg)

**Comment by adminant** [comment]
That's right, I have the same issue on Xiaomi phone with v 0.2.2 of plugin. BTW as I mentioned in parallel thread the Android virtual Pixel 2 API 28 device works nice.

**Comment by adminant** [comment]
#12

**Comment by pinkfish** [comment]
I fixed the crashing issues with the new version btw, should have fixed the issues around the camera not setting up correctly too.  It is doing the 90 degree flip in software now so the output should be rotated correctly now.  Hopefully anyway :). Looked good when I was testing, although not sure if it putting the right metadata into the stream for the size of the video right now.

**Comment by pinkfish** [comment]
I really should change the default streaming url so it doesn't run on my machines :)
