### ISSUE TITLE
Build errors on Android

### ISSUE THREAD

**Issue by ollydixon** [pinkfish/flutter_rtmppublisher#2]
While trying to build for Android I get the following errors.

I think you are building this plugin with a really old version of Flutter.
I think you need to upgrade your version of Flutter/Xcode/Android. (developer of this library)

```
flutter_rtmppublisher/android/src/main/kotlin/com/whelksoft/camera_with_rtmp/CameraPermissions.kt: (7, 17): Unresolved reference: core
flutter_rtmppublisher/android/src/main/kotlin/com/whelksoft/camera_with_rtmp/CameraPermissions.kt: (8, 17): Unresolved reference: core
flutter_rtmppublisher/android/src/main/kotlin/com/whelksoft/camera_with_rtmp/CameraPermissions.kt: (37, 13): Unresolved reference: ActivityCompat
flutter_rtmppublisher/android/src/main/kotlin/com/whelksoft/camera_with_rtmp/CameraPermissions.kt: (48, 17): Unresolved reference: ContextCompat
flutter_rtmppublisher/android/src/main/kotlin/com/whelksoft/camera_with_rtmp/CameraPermissions.kt: (53, 17): Unresolved reference: ContextCompat
```

**Comment by ollydixon** [comment]
The first fix is to add ```implementation 'androidx.annotation:annotation:1.1.0'``` to android/build.gradle

**Comment by pinkfish** [comment]
Uploading a new package that has these fixes.  Already had them locally :)

**Comment by pinkfish** [comment]
Just uploaded 0.1.4 which fixes the android issues.  Planning to look into some disconnect/heal issues tonight so it reconnects if there are issues with the network, right now it seems to drop and spin and not recover correctly.  Also is not cleaning up on dispose correctly it keeps running a thread in the background sending.
