### ISSUE TITLE
The stream remains in portrait mode even after changing the position of the phone to landscape, while the stream is going on.

### ISSUE THREAD

**Issue by aryanA101a** [pinkfish/flutter_rtmppublisher#64]
I used the example app.

**Comment by aravindhkumar23** [comment]
@aryanA101a I am also facing the same issue , did you find any workaround to this??

**Comment by aryanA101a** [comment]
Yes, I found a **fork** of pinkfish's plugin which is way better and updated.
[https://github.com/nhancv/flutter_rtmp_publisher](Link)
Goodluck using that👍

**Comment by aravindhkumar23** [comment]
Thanks for the information @aryanA101a will have a check on this and let you know about it.
