### ISSUE TITLE
Android have wrong orientation output

### ISSUE THREAD

**Issue by adorufus** [pinkfish/flutter_rtmppublisher#8]
hi, i have wrong orientation issue on android side. i have recorded on portrait position and the output result is landscape. can you help me how to fix this?

**Comment by adminant** [comment]
I have the same problem, rtmp stream comes as landscape though original position is portrait

**Comment by adorufus** [comment]
@adminant hi, if you know how to fix this please let me know

**Comment by adminant** [comment]
@adorufus Sorry, I don't know, I hope @pinkfish will fix this issue.
@pinkfish , could you help us?

**Comment by pinkfish** [comment]
It is do with the how the media encoder is encoding things.  I had it
around the other orientation to start with and it fails in the capture
part.  Right now it is putting in a hint on the encoder for the rotation
which should be working, although I also noticed it wasn't.

**Comment by pinkfish** [comment]
Just checking in a fix, or a workaround anyway.  If you useOpenGL in the arguments when creating the stream it will make an opengl surface and this will rotate the output to be portait mode.

**Comment by pinkfish** [comment]
The 0.2.0 version should fix this (is you use opengl anyway).

**Comment by adorufus** [comment]
@pinkfish sorry, but the playback view is so small (squared), can you help?

**Comment by adorufus** [comment]
and when i start the video streaming. i got error message that says "cannot use a surface that wasn't configured". i hope you can help me @pinkfish

**Comment by jmrboosties** [comment]
@pinkfish i see the flag in the RtmpCameraConnector, but there isnt a way i see to actually change that value from the flutter side
