### ISSUE TITLE
Camera preview freeze when rtmp streaming is active

### ISSUE THREAD

**Issue by adminant** [pinkfish/flutter_rtmppublisher#9]
When I start example app and select camera the preview shows camera picture ok.
But when I start rtmp streaming, the camera picture freeze, and one cannot see on the phone what is streamed.

**Comment by adminant** [comment]
Please help me with this problem, it stops me using this great plugin in my app.
The strange thing is that startVideoRecording works great, and the preview is not freezing, but startVideoStreaming is freezing preview, though I don't see major differences between these  methods in channel invoke part.

**Comment by pinkfish** [comment]
I am looking at this.  I think it is because it is not marking the frames as processed correctly.

**Comment by pinkfish** [comment]
Redoing how the streaming pieces are started/stopped right now too to make it work a bit better.

**Comment by adminant** [comment]
Thank you, great work! Now streaming preview works like a charm.
But now I couldn't stop video streaming, stopVideoStreaming method throws exception "No video is recording"

**Comment by pinkfish** [comment]
Ok, I think this is working correctly now, preview anyway.  Ahh, will look at stopVideoStreaming
